app/urls.py
from django.urls import re_path
from django.conf.urls.static import static
from django.conf import settings

from . import views

urlpatterns = [
    
    re_path(r'^$',views.index,name='index'),
    re_path(r'^new-hood/', views.create_hood, name='new-hood'),
    re_path(r'^join_hood/(?P<id>\w+)/', views.join_hood, name='join-hood'),
    re_path(r'^leave_hood/(?P<id>\w+)/', views.leave_hood, name='leave-hood'),
    re_path(r'^profile/(?P<id>\w+)/', views.profile, name='profile'),
    re_path(r'^update_profile/(?P<id>\w+)/', views.update_profile, name='update_profile'),
    re_path(r'^single_hood/(?P<id>\w+)/', views.single_hood, name='single-hood'),
    re_path(r'^add_post/(?P<id>\w+)/', views.hood_post, name='add-post'),
]   
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

business/urls.py
from . import views
from django.urls import path
from django.conf.urls.static import static
from neighbour import settings
from django.contrib.auth import views as auth_views

app_name = 'business'
urlpatterns = [
    path('search', views.Search, name="search"),
    path('addbusiness/<str:username>/', views.AddBusiness, name='addbusiness'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

neighbour/urls.py
from django.contrib import admin
from django.urls import re_path,include
from django.contrib.auth import views as view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^accounts/', include('django_registration.backends.one_step.urls'), name='register'),
    re_path(r'^accounts/', include('django.contrib.auth.urls')),
    re_path(r'^accounts/login', view.LoginView.as_view(template_name='registration/login.html'), name ='login'), 
    re_path(r'^logout', view.LogoutView.as_view(next_page='login')), 
    re_path(r'',include('app.urls')),
    re_path(r'business/',include('business.urls')),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/templates/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <title> Instagram Clone </title>
  {% block styles %}
  {% bootstrap_css %}
  {%endblock%}
  {% load static %}
  <!-- CSS only -->
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
</head>
<body style="background-image: linear-gradient(black, gray); background-attachment: fixed;

color:white;">
   
    {% block content %}{%endblock%}
    {% include "navbar.html" %}

    {% block scripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
     {% bootstrap_javascript %}
    {% endblock %}
</body>
</html>

app/templates/hood_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container bg-white newhood">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <h3 class="text-center">Add Neighborhood Post</h3>
            <form action="" method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <button style="margin-top: 1%;" class="btn btn-sm btn-success">Post</button>
            </form>
        </div>
        <div class="col-md-1"></div>
    </div>

</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
       
        {% for hood in all_hoods %}
        <div class="col-md-1"></div>
        <div class="col-md-5">
            <div class="card mb-4" style="min-height:340px; margin-top:3% ;">
                <img src="{{ hood.logo.url }}" width="400" class="card-img-top" alt="{{ hood.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ hood.name }}  ({{hood.location}}) <span class="ml-4">{{hood.occupants}} member{{hood.occupants.count|pluralize}}</span></h5>
                    <p class="card-text">{{hood.description}}</p>
                    {% if request.user.profile.neighbourhood == hood %}
                    <a href="{% url 'leave-hood' hood.id %}" class="btn btn-danger btn-sm">Leave Hood</a>
                    {% elif not request.user.profile.neighbourhood %}
                    <a href="{% url 'join-hood' hood.id %}" class="btn btn-primary btn-sm">Join Hood</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/navbar.html
<header id="header" style="position: fixed; top:0%;" class="header">
    <nav class="nav">
      <ul class="nav-list">
        <li class="nav-item">
          <a href="/" class="nav-link">
            <i class="fa fa-home icon"></i>
            <span class="text">Home</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'new-hood' %}" class="nav-link">
            <i class="fa fa-address-book icon"></i>
            <span class="text"> Add-Neighbourhood</span>
          </a>
        </li>
        
        {% if user.profile.neighbourhood %}
        <li class="nav-item">
            <a href="{% url 'single-hood' user.profile.neighbourhood.id %}" class="nav-link">
                <i class="fa fa-paper-plane"></i> <span class="text">&nbsp;
                &nbsp;{{user.profile.neighbourhood.name}}</span>
            </a>
        </li>
        {% else %}
        <li class="nav-item">
            <a href="" class="nav-link"> <span class="text">&nbsp;
                No Hood Yet</span>
            </a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a href="{% url 'profile' user.id  %}" class="nav-link">
            <i class="fa fa-user icon"></i>
            <span class="text">Profile</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'update_profile' user.id  %}" class="nav-link">
            <i class="fa fa-cog icon"></i>
            <span class="text">Update Profile</span>
          </a>
        </li>
        {% if user.profile.neighbourhood %}
        <li class="nav-item">
          <a href="{% url 'business:addbusiness' user.username %}" class="nav-link">
            <i class="fa fa-briefcase icon"></i>
            <span class="text">Add Business</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="logout" class="nav-link">
            <i class="fa fa-sign-out icon"></i>
            <span class="text">Sign out</span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="logout" class="nav-link">
            <i class="fa fa-sign-out icon"></i>
            <span class="text">Sign out</span>
          </a>
        </li>
      {% endif %}
     
      </ul>
    </nav>
    <a id="btn-navig" class="btn-navig" href="#">
      <i class="fa fa-bars open icon"></i>
      <i class="fa fa-close close icon"></i>
    </a>
    </header>
<script>
const headerElm = document.getElementById("header");
const btnNavig = document.getElementById("btn-navig");

btnNavig.addEventListener("click", function () {
  headerElm.classList.toggle("optimize");
});
</script>

app/templates/newhood.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container bg-white newhood">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <h3 class="text-center">Add Your Neighborhood Here</h3>
            <form action="" method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                <br/>
                <button  type="submit" style="margin-top: 1%;" class="btn btn-sm btn-success">Add Hood</button>
            </form>
            <br/>
        </div>
        <div class="col-md-1"></div>
    </div>

</div>
{% endblock %}

app/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container bg-white newhood">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <h3 class="text-center">Update Your Profile Here</h3>
            <form action="" method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                {{ prof_form|crispy }}
                <button style="margin-top: 1%;" class="btn btn-sm btn-success">Update Profile</button>
            </form>
        </div>
        <div class="col-md-1"></div>
    </div>

</div>
{% endblock %}

app/templates/single_hood.html
{% extends 'base.html' %}
{% block content %}
<style>
 

.input {
    padding: 10px;
    width: 300px;
    height: 80px;
    background: none;
    border: 4px solid #ff004c;
    border-radius: 50px;
    box-sizing: border-box;
    font-family: Comic Sans MS;
    font-size: 26px;
    color: #ff004c;
    outline: none;
    transition: .5s;
}
.box:hover input{
    width: 550px;
    background: #414142;
    border-radius: 10px;
}
.box i{
    position: absolute;
    top: 50%;
    right: 15px;
    transform: translate(-50%,-50%);
    font-size: 26px;
    color: #ffd52d;
    transition: .2s;
}
.box:hover i{
    opacity: 0;
    z-index: -1;
}
</style>
<div class="container" style="margin-top:4%">
    <div class="row">
    
            <div class="card mb-3">
                <div class="row no-gutters">
                    <div class="col-md-5"> 
                        <img src="{{ hood.logo.url }}" width="400" class="card-img" alt="...">
                    </div>
                    <div class="col-md-7">
                        <div class="card-body">
                            <h5 class="card-title tt">{{ hood.name }} ({{hood.location}})
                            </h5>
                            <h6 class="card-text">
                                <span><strong>{{hood.occupants}}</strong> Members{{hood.occupants.count|pluralize}}</span>
                            </h6>
                            <p class="card-text">{{hood.description}}</p>
                            <p class="card-text"><span class="text-info">Police Tell</span>
                                &nbsp;<strong>{{hood.police_number}}</strong> |
                                <span class="text-info">Hospital Tell</span> <strong>{{hood.health_tell}}</strong></p>
                            <p class="card-text">Administrator: <small class="text-muted">
                                {{ hood.user.user.username }}</small></p>
                                <a href="{% url 'add-post' hood.id %}">
                                    <h2>Add Post</h2>
                                </a>
                        </div>
                    </div>
                </div>
            </div>
        

        <h3 class="D-block mx-auto tt">Posts</h3>
                    {% for post in posts %}
                    <div class="col-md-4" style="margin-top: 1%;">
                        <div class="card mb-4 hpost">
                            <div class="card-body">
                                <h5 class="card-title">{{post.title}}</h5>
                                <p class="card-text">" {{post.post}} "
                                </p>
                                <p class="card-text">By: <small class="text-white">
                                    {{ post.user.user.username|title }}</small> <small style="float:right">{{post.date|date}}</small>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <center>    
                        {% if messages %}
                            {% for message in messages %} 
                            <div class="alert {{message.tags}} m-1" role="alert" style="font-size: medium; margin-bottom: 30px;">
                                {{message}}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            {% endfor %} 
                        {% endif %}
                    </center>
            
                    <!-- Breadcrumb -->
                
                    
                        <div class="box ml-auto">
                             <form name="search" method=POST action="{% url 'business:search' %}">
                                 {% csrf_token %}
                                 <input type="search" class="input" aria-label="Search" placeholder="Search Business" name="search" 
                                 onmouseout="this.value = ''; this.blur();">
                                 
                             </form>
                             
                         </div> 
                     
                    <!-- /Breadcrumb -->
                  
                    {% if businesses %}
                        <div class="row" style="margin-left: 1%;">
                            <h3 class="D-block mx-auto tt">Businesses</h3>
                            {% for business in businesses %}
                            <div class="col-sm-4">
                                <div class="card" style="margin-bottom: 30px;">
                                    <div class="card-body">
                                        <h5 class="card-title">{{ business.name }}</h5>
                                        <p class="text-muted" style="font-size: small;">
                                            Neighbourhood: {{business.neighbourhood.name}}
                                            <span class="text-dark">
                                                <b>
                                                    
                                                        {{ business.neighbourhood.title }}   
                                            
                                                </b>
                                            </span>
                                        </p>
                                        <p class="card-text">{{ business.description|truncatewords:45 }}</p>
                                        <div class="" style="float:left">
                                            <h6><span  style="font-weight: lighter; font-size: small;">Email Address: <b>{{ business.email }}</b></span></h6>
                                        </div>
                                        <br>
                                        <div class="" style="float:right">
                                            
                                                <h6><span class="badge badge-primary">{{ business.neighbourhood }}</span></h6>
                                        
                                        </div>
                                        <br>
                                        <hr>
                                        <div class="d-flex flex-row user-info">
                                            {% if business.owner.profile_picture.url %}
                                                <img class="rounded" src="{{ business.owner.profile_picture.url }}" height="40" width="40">
                                            {% else %}
                                                <img class="rounded" src="https://www.pngall.com/wp-content/uploads/5/Profile-PNG-File.png" height="40" width="40">
                                            {% endif %}
                                            <div class="d-flex flex-column justify-content-start ml-2">
                                                <a href="#">
                                                    <span class="name"><b>{{ business.owner.user.first_name }} {{ business.owner.user.last_name }}</b></span>
                                                </a>
                                                <span class="text-muted" style="font-size: small;"><i class="fas fa-calendar-alt"></i> {{ business.date_created }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    {% else %}
                        <div class="col-sm-12" style="margin-top: 20px;">
                            <div class="content text-center">
                                <svg xmlns="http://www.w3.org/2000/svg" width="72" height="72" viewBox="0 0 24 24" style="fill: rgba(0, 0, 0, 1);"><path d="M20 6h-3V4c0-1.103-.897-2-2-2H9c-1.103 0-2 .897-2 2v2H4c-1.103 0-2 .897-2 2v11c0 1.103.897 2 2 2h16c1.103 0 2-.897 2-2V8c0-1.103-.897-2-2-2zm-5-2v2H9V4h6zM4 8h16v4h-3v-2h-2v2H9v-2H7v2H4V8zm0 11v-5h3v2h2v-2h6v2h2v-2h3.001v5H4z"></path></svg>
                                <br>
                                <h4 class="text-dark py-3">No Associated Businesses Found</h4>
                                <a href="{% url 'business:addbusiness' user.username %}" name="AddBusiness">
                                    <button type="submit" class="btn btn-primary btn-md" style="margin-right: 20px;"><i class="fa-solid fa-plus"></i> Add A Business</button>
                                </a>
                                <br>
                            </div> 
                        </div>
                    {% endif %}
                
    </div>
</div>
{% endblock %}

app/templates/user_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container ">
    <div class="row" style="margin-top: 15%; margin-left: 15%;">
        <div class="col-md-1"></div>
        <div class="col-md-1"></div>
        <div class="col-md-4"> <img class="rounded-circle account-img d-block mx-auto" src="{{ user.profile.profile_picture.url }}" style="border-radius: 50%; width:70%;"></div>
        <div class="col-md-3" style="margin-top: 5%; font-size: x- large;">
            <p class="text-center">Name: {{user.username|upper}}</p>
            <p class="text-center"> {{user.email}}</p>
            {% if request.user.profile.neighbourhood %}
            <p class="text-center">My Hood <a class="btn btn-sm btn-info" href="{% url 'single-hood' user.profile.neighbourhood.id %}">{{ user.profile.neighbourhood.name }}</a>
            </p>
            {% endif %}
        </div>
        <div class="col-md-3"></div>
    </div>


</div>
{% endblock %}